### PR TITLE
Add GDNative implementation of QuadTreeLod in Rust

### PR DESCRIPTION
**Pull request by Demindiro**
The profiler tricked me into believing QuadTreeLod._update() was taking up a significant amount of time (~8ms vs actually ~1ms), so I wrote a native implementation of the class before realizing why the seemingly high time usage seemed off.

I wrote it in Rust as IME it's much less error-prone than C or C++ and I've found godot-rust a lot easier to set up too.

To use it, comment `const QuadTreeLod = preload("./util/quad_tree_lod.gd")` out and uncomment `const QuadTreeLod = preload("./util/quad_tree_lod.gdns")`. There is probably a cleaner way to do this but I don't know how.

I also have included binaries for Linux, OSX, and Windows.

### CODE REVIEW

**Comment by Calinou** [comment]
Out of curiosity, how did you compile the library for all platforms? I suggest including a README documenting how to do this for future contributors.

**Comment by Demindiro** [comment]
> Out of curiosity, how did you compile the library for all platforms? I suggest including a README documenting how to do this for future contributors.

For OS X I installed [OSXCross](https://github.com/tpoechtrager/osxcross) first.

You need a Rust compiler (installed with `rustup` so you have the latest) version and then added the following targets:
```
rustup target add x86_64-unknown-linux-gnu
rustup target add x86_64-apple-darwin
rustup target add x86_64-pc-windows-gnu
```

I then compiled the binaries with these commands (I put them in a Makefile in another project):
```
cargo build --release --target x86_64-unknown-linux-gnu
cargo build --release --target x86_64-apple-darwin
cargo build --release --target x86_64-pc-windows-gnu
```

The binaries will be located under `target/$TARGET`

---

I'll add/update a README tomorrow as there are some other things I want to finish first.

**Comment by Zylann** [comment]
Thank you for your contribution, however I have mixed feelings about it.

1) Now the plugin has an additional language dependency. I like self-contained projects using only what's necessary, but now a Rust toolchain is also needed (with all the extra files mixed up with the C++ setup).

2) Because of this, if more parts of the plugin have to be implemented natively, they can't communicate with each other natively. At least not without extra computer/coder overhead.

3) Exports now need an additional dynamic library. It contains something very small but on some platforms a large part of it is extra runtime stuff, which increases the size of exports by several megabytes.

4) At the moment I'm not a Rust maintainer. I mainly focus on GDScript and C++ languages, so I'm not able to review this as properly. Also if this library is included I might not be able to keep it up to date.
Some comments I can do however:
- `#[inherit(Object)]`: QuadTreeLod is used like a Reference. With an Object it will leak.

5) As you said, QuadTreeLod isn't entirely responsible for the times you get in the profiler. So it seems adding all this really isn't the best choice. Did your library improve performance? Did you see what actually makes it slow?

6) About the `preload`: this can be solved the same way I did for ImageUtils. Two implementations, one GDScript, one GDNative, and use a factory instead. But again this is made more complex by the fact the new class isn't simply located in the same assembly. This design is used because sometimes users have issues related to the GDNative libs, and it allows to keep their project working. It also allows web exports to work.

7) Last point is a bit more hypothetical: I was thinking of solving the actual slow part (min/max retrieval) by putting the data into an Image so I could use ImageUtils. There is also a bit of bad algorithmic choices rather than language slowness. But all of this might be changed one day, if a GPU implementation like clipmaps is introduced. LOD would no longer need to be handled on the CPU. I've seen other terrains systems do this and it seems to be a better evolution.

**Comment by Demindiro** [comment]
> * Now the plugin has an additional language dependency. I like self-contained projects using only what's necessary, but now a Rust toolchain is also needed (with all the extra files mixed up with the C++ setup).
> 
> * Because of this, if more parts of the plugin have to be implemented natively, they can't communicate with each other natively. At least not without extra computer/coder overhead.
>
> * Exports now need an additional dynamic library. It contains something very small but on some platforms a large part of it is extra runtime stuff, which increases the size of exports by several megabytes.
>
> * At the moment I'm not a Rust maintainer. I mainly focus on GDScript and C++ languages, so I'm not able to review this as properly. Also if this library is included I might not be able to keep it up to date.

Understandable.

> Some comments I can do however:
>
> *   `#[inherit(Object)]`: QuadTreeLod is used like a Reference. With an Object it will leak.

Thanks! I overlooked that.

> As you said, QuadTreeLod isn't entirely responsible for the times you get in the profiler. So it seems adding all this really isn't the best choice. Did your library improve performance? Did you see what actually makes it slow?

There isn't actually that makes it (too) slow. It just showed up as taking up a lot of time because the profiler doesn't profile recursive functions correctly in inclusive mode. However, it still takes roughly 0.5ms - 1.0ms less time than the GDScript implementation so I figured it was worth making a PR anyways.

> * About the `preload`: this can be solved the same way I did for ImageUtils. Two implementations, one GDScript, one GDNative, and use a factory instead which can choose between them. But again this is made more complex by the fact the new class isn't simply located in the same assembly. This design is used because sometimes users have issues related to the GDNative libs, and it allows to keep their project working. It also allows web exports to work, or just "turn of GDNative stuff" easily.

That doesn't seem like it would with static typing easily though I think? (Not that it seems to work for GDNative anyways...) But I agree that seems to be the cleanest solution.

No comment on the last part as I don't have enough experience in that field.

**Comment by Zylann** [comment]
> it still takes roughly 0.5ms - 1.0ms less time than the GDScript implementation so I figured it was worth making a PR anyways.

Good to know, GDScript doesnt help much with that. There are ways to mitigate this by reducing split scale and increasing chunk size.

> That doesn't seem like it would with static typing easily though I think?

Oh definitely, static typing won't work^^ But since it's an internal, it's not as bad as if it was exposed directly to users.

**Pull request closed without merging**
